### PR TITLE
Attempt to SSO

### LINKED ISSUE #19: Enable SSO
We could get inspiration from the Rainloop package : https://github.com/YunoHost-Apps/rainloop_ynh/blob/master/sources/sso/sso.php

### PR DESCRIPTION
**Pull request by Tagadda**
## Problem

- Fix #19 

## Solution

- Generate `conf/application.ini` in `scripts/install` and `scripts/upgrade`
- Move the app in a subfolder `$install_dir/app`
- Setup `sso.php` at `$install_dir/index.php` https://github.com/the-djmaze/snappymail/issues/278#issuecomment-1062858896

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Tagadda** [comment]
I wonder if we should move the whole app in a `/app/` subdirectory as RainLoop was.
It would be way simpler to handle SSO and solve the issue mentioned about the infinite redirection when `visitors` have assess.
Any opinion ?

**Comment by Tagadda** [comment]
ping @ericgaspar

**Comment by ericgaspar** [comment]
If this allows the use of the SSO, go go go

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
`change_url` fails... :/
```
DEBUG - + ynh_add_config --template=../sources/sso.php --destination=/var/www/snappymail/index.php
WARNING The provided template ../sources/sso.php doesn't exist
```

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@Tagadda Are you able to login to the Admin Panel?

**Comment by ericgaspar** [comment]
`application.ini` needs to be regenerated in `change_url` script

**Comment by Tagadda** [comment]
> Are you able to login to the Admin Panel?

@ericgaspar I didn't try this yet, I hope those lines are not a problem:
https://github.com/YunoHost-Apps/snappymail_ynh/blob/8fe5c58491a8d3c11b76db872ea904970e958ab1/conf/application.ini#L74-L76

**Comment by ericgaspar** [comment]
!testme

**Comment by Tagadda** [comment]
Let's merge to testing and ask for feedback?

**Pull request merged**
